/* ===== Datos del viaje EUROPA 2026 — Tin & Memi ===== */

const TRIP = {
  title: "Europa 2026",
  subtitle: "Tin & Memi",
  dateRange: "24 de agosto — 16 de septiembre",
  route: ["Buenos Aires", "Londres", "Mykonos", "Bari", "Ostuni", "Roma", "París", "Madrid", "Buenos Aires"],
};

const PENDING = [
  {
    title: "Alojamiento en Roma",
    detail: "4 noches (06/09 al 10/09) sin hotel elegido todavía.",
  },
  {
    title: "Auto de alquiler en Puglia",
    detail: "Para moverse entre Bari y Ostuni (04/09 al 06/09). Todavía no se reservó ninguna empresa.",
  },
  {
    title: "Alojamiento en Madrid",
    detail: "2 noches (13/09 al 15/09) sin reserva concreta. Evaluando la zona de Chamberí.",
  },
];

/* Itinerario día por día */
const ITINERARY = [
  { date: "Lun 24/08", city: "Buenos Aires → Londres", note: "Memi despega de EZE 21:10 hs rumbo a Londres (American Airlines). Llega a LHR el 25/08 por la noche.", tag: "vuelo", accent: "london" },
  { date: "Mar 25/08", city: "Londres", note: "Memi llega a Londres por la noche. Check-in en easyHotel London City Shoreditch disponible desde las 15:00 hs. Tin todavía en Buenos Aires.", tag: "estadia", accent: "london" },
  { date: "Mié 26/08", city: "Londres", note: "Día en Londres (Memi).", tag: "estadia", accent: "london" },
  { date: "Jue 27/08", city: "Buenos Aires → Madrid", note: "Tin vuela EZE → MAD, 13:25 hs, Plus Ultra PU502 (vuelo directo nocturno).", tag: "vuelo", accent: "london" },
  { date: "Vie 28/08", city: "Madrid → Londres", note: "Tin llega a Madrid 06:30 hs y continúa MAD → LHR, British Airways BA457 (10:35–12:00). Se reencuentra con Memi en Londres.", tag: "vuelo", accent: "london" },
  { date: "Sáb 29/08", city: "Londres", note: "Londres, juntos.", tag: "estadia", accent: "london" },
  { date: "Dom 30/08", city: "Londres", note: "Londres, juntos.", tag: "estadia", accent: "london" },
  { date: "Lun 31/08", city: "Londres", note: "Londres, juntos.", tag: "estadia", accent: "london" },
  { date: "Mar 01/09", city: "Londres → Mykonos", note: "Checkout 10:00 hs. Vuelo Londres-Luton (LTN) → Mykonos (JMK), 15:05–21:00, Wizz Air.", tag: "vuelo", accent: "mykonos" },
  { date: "Mié 02/09", city: "Mykonos", note: "Día en Mykonos.", tag: "estadia", accent: "mykonos" },
  { date: "Jue 03/09", city: "Mykonos → Bari", note: "Checkout 11:00 hs. Vuelo Mykonos → Bari, 22:55–23:35, Volotea V7 1605.", tag: "vuelo", accent: "puglia" },
  { date: "Vie 04/09", city: "Bari → Ostuni", note: "Traslado en auto de alquiler (a gestionar) desde Bari hacia Ostuni. Check-in en Ostuni.", tag: "traslado", accent: "puglia" },
  { date: "Sáb 05/09", city: "Ostuni", note: "Día en Ostuni, Puglia.", tag: "estadia", accent: "puglia" },
  { date: "Dom 06/09", city: "Ostuni → Roma", note: "Checkout y regreso a Bari. Tren Bari Centrale → Roma Termini, 18:30–23:05 (ItaliaRail).", tag: "tren", accent: "roma" },
  { date: "Lun 07/09", city: "Roma", note: "Día en Roma.", tag: "estadia", accent: "roma" },
  { date: "Mar 08/09", city: "Roma", note: "Día en Roma.", tag: "estadia", accent: "roma" },
  { date: "Mié 09/09", city: "Roma", note: "Día en Roma.", tag: "estadia", accent: "roma" },
  { date: "Jue 10/09", city: "Roma → París", note: "Checkout. Vuelo Roma-Fiumicino (FCO) → París-Orly (ORY), 09:55–12:05, EasyJet EJU4934.", tag: "vuelo", accent: "paris" },
  { date: "Vie 11/09", city: "París", note: "Día en París.", tag: "estadia", accent: "paris" },
  { date: "Sáb 12/09", city: "París", note: "Día en París.", tag: "estadia", accent: "paris" },
  { date: "Dom 13/09", city: "París → Madrid", note: "Checkout. Vuelo París-Orly (ORY) → Madrid, 09:40–11:50, Transavia TO4632.", tag: "vuelo", accent: "madrid" },
  { date: "Lun 14/09", city: "Madrid", note: "Día en Madrid.", tag: "estadia", accent: "madrid" },
  { date: "Mar 15/09", city: "Madrid → Buenos Aires", note: "Checkout. Vuelo MAD → EZE, 22:55 hs, Plus Ultra PU501 (llega 06:45 del día siguiente).", tag: "vuelo", accent: "madrid" },
  { date: "Mié 16/09", city: "Buenos Aires", note: "Llegada a Buenos Aires, 06:45 hs. Fin del viaje.", tag: "llegada", accent: "madrid" },
];

/* Alojamiento por destino */
const DESTINATIONS = [
  {
    city: "Londres",
    country: "Reino Unido",
    accent: "london",
    icon: "london",
    dates: "24/08 al 01/09 · 8 noches",
    status: "confirmado",
    name: "easyHotel London City Shoreditch",
    detail: "Habitación doble · 80 Old Street, Greater London, England EC1V 9AZ, United Kingdom",
    platform: "Airbnb",
    code: "HMDKECPZCY",
    extra: "Check-in martes 25/08 15:00 hs · Checkout martes 01/09 10:00 hs · 2 adultos",
    cost: "USD 989",
  },
  {
    city: "Mykonos",
    country: "Grecia",
    accent: "mykonos",
    icon: "mykonos",
    dates: "01/09 al 03/09 · 2 noches",
    status: "confirmado",
    name: "Room in Mikonos",
    detail: "Anfitrión Nikolaos · Panachrantou 20",
    platform: "Airbnb",
    code: "HM88YD9K22",
    extra: "Checkout jueves 03/09 11:00 hs · 2 huéspedes",
    cost: "USD 650",
  },
  {
    city: "Bari",
    country: "Italia",
    accent: "puglia",
    icon: "puglia",
    dates: "03/09 al 04/09 · 1 noche",
    status: "confirmado",
    name: "Habitación en Bari",
    detail: "Anfitrión CconfortHotels",
    platform: "Airbnb",
    code: null,
    extra: "2 huéspedes",
    cost: "USD 138",
  },
  {
    city: "Ostuni",
    country: "Italia (Puglia)",
    accent: "puglia",
    icon: "puglia",
    dates: "04/09 al 06/09 · 2 noches",
    status: "confirmado",
    name: "Casa en Ostuni",
    detail: "Anfitriona Antonella",
    platform: "Airbnb",
    code: null,
    extra: null,
    cost: "USD 226 (estimado)",
  },
  {
    city: "Roma",
    country: "Italia",
    accent: "roma",
    icon: "roma",
    dates: "06/09 al 10/09 · 4 noches",
    status: "pendiente",
    name: "Sin hotel elegido todavía",
    detail: "Falta buscar y reservar alojamiento.",
    platform: null,
    code: null,
    extra: null,
    cost: null,
  },
  {
    city: "París",
    country: "Francia",
    accent: "paris",
    icon: "paris",
    dates: "10/09 al 13/09 · 3 noches",
    status: "confirmado",
    name: "Alojamiento confirmado",
    detail: null,
    platform: "Booking.com",
    code: null,
    extra: null,
    cost: "USD 700",
  },
  {
    city: "Madrid",
    country: "España",
    accent: "madrid",
    icon: "madrid",
    dates: "13/09 al 15/09 · 2 noches",
    status: "pendiente",
    name: "Sin reserva concreta",
    detail: "Evaluando la zona de Chamberí.",
    platform: null,
    code: null,
    extra: null,
    cost: null,
  },
];

/* Vuelos y trenes */
const TRANSPORTS = [
  {
    route: "Buenos Aires (EZE) → Londres (LHR)",
    who: "Memi",
    when: "Sale lunes 24/08 21:10 hs · Llega martes 25/08 por la noche",
    detail: "American Airlines",
    platform: "American Airlines (directo)",
    code: "QTAULE",
    cost: "USD 778",
    accent: "london",
  },
  {
    route: "Buenos Aires (EZE) → Madrid (MAD)",
    who: "Tin",
    when: "Jueves 27/08 13:25 hs → Viernes 28/08 06:30 hs",
    detail: "Plus Ultra Líneas Aéreas PU502 · directo (12h05m) · incluye el regreso MAD → EZE",
    platform: "Booking.com",
    code: "Ref. cliente 40-979728780 · PIN 5301 · Reserva RJRNPU",
    cost: "USD 1665 (ida y vuelta)",
    accent: "london",
  },
  {
    route: "Madrid (MAD) → Londres (LHR)",
    who: "Tin",
    when: "Viernes 28/08, 10:35 → 12:00",
    detail: "British Airways BA457",
    platform: "British Airways (directo)",
    code: "ZZ3FRN",
    cost: "USD 113",
    accent: "london",
  },
  {
    route: "Londres-Luton (LTN) → Mykonos (JMK)",
    who: "Memi y Tin",
    when: "Martes 01/09, 15:05 → 21:00",
    detail: "Wizz Air W95491",
    platform: "Wizz Air (directo)",
    code: "Memi: FRL9RK · Tin: IIBVXY",
    cost: "USD 275 (ambos)",
    accent: "mykonos",
  },
  {
    route: "Mykonos → Bari",
    who: "Memi y Tin",
    when: "Jueves 03/09, 22:55 → 23:35",
    detail: "Volotea V7 1605",
    platform: "Volotea (directo)",
    code: "OBKZGT",
    cost: "USD 225",
    accent: "puglia",
  },
  {
    route: "Tren Bari Centrale → Roma Termini",
    who: "Memi y Tin",
    when: "Domingo 06/09, 18:30 → 23:05",
    detail: "Tren",
    platform: "ItaliaRail",
    code: "Orden TRE-UF0K-326Z-5K69-B · Reserva LZMG4N",
    cost: "USD 145",
    accent: "roma",
  },
  {
    route: "Roma-Fiumicino (FCO) → París-Orly (ORY)",
    who: "Memi y Tin",
    when: "Jueves 10/09, 09:55 → 12:05",
    detail: "EasyJet EJU4934",
    platform: "EasyJet (directo)",
    code: "KCW3QPT",
    cost: "USD 290",
    accent: "paris",
  },
  {
    route: "París-Orly (ORY) → Madrid",
    who: "Memi y Tin",
    when: "Domingo 13/09, 09:40 → 11:50",
    detail: "Transavia TO4632",
    platform: "Transavia (directo)",
    code: "TB6U5C",
    cost: "USD 250",
    accent: "madrid",
  },
  {
    route: "Madrid (MAD) → Buenos Aires (EZE)",
    who: "Memi y Tin",
    when: "Martes 15/09 22:55 hs → Miércoles 16/09 06:45 hs",
    detail: "Plus Ultra PU501",
    platform: "Booking.com",
    code: "Memi — Ref. cliente 40-979995402 · PIN 9086 · Reserva YHEZTN",
    cost: "USD 659",
    accent: "madrid",
  },
];

/* Gastos ya pagados */
const EXPENSES = [
  { item: "Vuelo Memi — ida (EZE-LHR)", cost: 778 },
  { item: "Vuelo Tin — ida y vuelta (EZE-MAD-EZE)", cost: 1665 },
  { item: "Vuelo Tin — Madrid-Londres", cost: 113 },
  { item: "Hotel Londres", cost: 989 },
  { item: "Vuelos Londres-Mykonos (ambos)", cost: 275 },
  { item: "Hotel Mykonos", cost: 650 },
  { item: "Pasajes Mykonos-Bari", cost: 225 },
  { item: "Cuarto en Bari", cost: 138 },
  { item: "Ostuni (estimado)", cost: 226 },
  { item: "Tren Bari-Roma", cost: 145 },
  { item: "Pasajes Roma-París", cost: 290 },
  { item: "Hotel París", cost: 700 },
  { item: "Pasaje París-Madrid", cost: 250 },
  { item: "Vuelo Memi — vuelta (MAD-EZE)", cost: 659 },
];

const EXPENSES_PENDING = ["Hotel en Roma", "Hotel en Madrid", "Auto de alquiler en Puglia"];
